### ISSUE TITLE
[epic] [validation] Unified validation report format for validating metadata and data

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/software#30]
*This epic sets out evolving thoughts on how we do validation of metadata and data in data resources and data packages and the technical framework for that, in particular a common reporting format.*

## Tasks

* [ ] Write user stories
* [ ] Document existing approaches in various libraries
* [ ] Propose a common validation reporting format

## User Stories

As Publisher I want to be able check parsing, metadata and data all together and independently so that my data (package) is valid and can be used by other tools

* By default I want to check the data (I don't get about the metadata much??)
* Data = file (primary) + data package / dataset (secondary)

As a User I want to know if i fail to parse the file so that I can correct it

As a User I want to know if metadata is valid so that I can correct it ...

As a Publisher I want to know if my data is valid so that I can correct it ...

* want to know where and what is wrong and how i can fix it
  * where: what file, what row (show me)
  * what is wrong: what is the issue
  * how i can fix: ...
* want to be able to check one file at a time

## Implementation

What should the validation report look like on a Data Package?

Here's a suggestion:

```javascript
valid: true | false
// simple parse errors with datapackage.json
parse: {
  message: 
  line: ...
}
// validation errors with metadata
metadata: {
  errors: ...
  warnings: ...
}
// data validation errors
// each entry would follow goodtables validation report spec (tbc)?
resources: [
  {
    "name": // name of resource
    goodtable style report ... - https://github.com/frictionlessdata/goodtables-py#validate
  ...
  }
]
```

### Error / Warning object

```
{
  "message": "Header in column 3 is blank",
   "code": "blank-header",
  "row-number": null,
  "row": null,
  "column-number": 3,
}
```

Cases:

* "Header" errors
* "Row" errors
* Other ??

*TODO*: clarifying what is tabular-specific

### GoodTables report format

* https://github.com/frictionlessdata/goodtables-py#validation-report-format
  * https://github.com/frictionlessdata/goodtables-py#validate
  * JSON Schema: https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/schemas/report.json
* List of errors: https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json

Sample:

```
{
    "time": 0.009,
    "error-count": 1,
    "warnings": [
        "Table \"data/invalid.csv\" inspection has reached 1 error(s) limit"
    ],
    "preset": "table",
    "valid": false,
    "tables": [
        {
            "errors": [
                {
                    "row-number": null,
                    "message": "Header in column 3 is blank",
                    "row": null,
                    "column-number": 3,
                    "code": "blank-header"
                }
            ],
            "error-count": 1,
            "headers": [
                "id",
                "name",
                "",
                "name"
            ],
            "scheme": "file",
            "row-count": 2,
            "valid": false,
            "encoding": "utf-8",
            "time": 0.007,
            "schema": null,
            "format": "csv",
            "source": "data/invalid"
        }
    ],
    "table-count": 1
}
```

### tableschema-js

See this commit message for some notes based on my investigations https://github.com/datahq/data-cli/commit/ee7589a3ab4af85933faebb4184f0fc3e015ec0d

### data-package-validate

This is the structure in the original https://github.com/oki-archive/datapackage-validate-js

```javascript
{
  valid: true | false,
  errors: [
    {
      // every error has a message
      message: 'Invalid JSON: ...'
      // JSON errors come from json-lint and will also have
      line: 
    },
    {
      message: 'Array is too short (0), minimum 1',
      // schema errors come from schema validator and include additiona
      // path in input JSON
      dataPath: '/resources',
      // path in schema
      schemaPath: '/properties/resources/minItems',
    },
    ...
  ]
  warnings: [
    {
      message: 'No title field'
    },
    ...
  ]
};
```

**Comment by Stephen-Gates** [comment]
Some user stories at https://github.com/Stephen-Gates/data-quality-pattern/blob/master/user-stories.md

**Comment by philtweir** [comment]
In setting up an open source validation-as-a-service platform, we have needed a consistent JSON validation reporting approach to go across geographical and tabular data, and apply to as-yet-unseen formats as far as reasonably possible.

We have based off the goodtables reporting approach, but in general, have allowed context-specific information contained in appropriate fields (such as error-location-in-file as an object, rather than row/col, or contextual information object, rather than row array), pushing the burden of interpretation to any parsers/renderers that understand that given context.

This had been going on in parallel, so thanks @vitorbaptista and @Stephen-Gates for pointing us to these discussions! In particular, we had not considered metadata errors in top-level approach metadata errors but @rufuspollock's approach looks great.

It would be really good if we can align our work with the general consensus - we have a Northern Ireland based Coding Challenge coming up next month, encouraging interested coders to submit some simple checkers for local open data (inc non-tabular), which will require output in a standard format. The more we can make sure that format is in line with the evolving discussions here, the better!

This suggested spec had been put together before we were aware of this thread, but may be useful for comment/context : https://paper.dropbox.com/doc/Proposal-Data-Quality-Reporting-Specification-r9TfEutMpK8j9RVKZLJsm

**Comment by Stephen-Gates** [comment]
Thanks @philtweir - I'll have a read and comment 👍

**Comment by Stephen-Gates** [comment]
@philtweir I wonder if we can go one step further for your challenge and fold in data quality and statistics into the `info` type messages? 

As discussed in [data quality pattern](https://github.com/Stephen-Gates/data-quality-pattern/blob/master/data-quality-pattern.md), you could have a set of metrics that return 
- a measure (e.g. mean), 
- a value and type from the data (e.g. minimum, type:date)
- or perhaps an array (e.g. outliers)

**Comment by philtweir** [comment]
Thanks @Stephen-Gates - your approach to incorporating metrics looks logical to me too -- it's not something we had thought about originally, but I agree that makes a lot of sense. Will bring it up with the Challenge setters at this end! (ping to @martinnaughton also)

**Comment by rufuspollock** [comment]
@Stephen-Gates @philtweir I have updated the description quite a bit with more material from good tables report format and pulling out some key parts.

I think the focus at the moment should be the actual error messages rather than the general metadata.

**Comment by philtweir** [comment]
Great - thanks @rufuspollock , that's useful clarification.

On your second point, do you mean that the focus should currently be:

 - (within this issue), the reporting structure for error messages (i.e. name) rather than the metadata about the messages (i.e. file-location, associated entity),
or
 - (more generally), on that the primary focus should be enumerating available error messages (https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json), rather than focusing on how we structure the reporting of that (this issue)?

**Comment by rufuspollock** [comment]
@philtweir i mean that it should focus on the whole error object including the file location etc (but less on the general metadata e.g. the time, total error count etc)

**Comment by flashharry82** [comment]
I have been working on our coding challenge with @philtweir and he suggested adding some of our current work-in-progress. The schema that we are planning to use for the challenge is a cut-down version that encompasses a lot of the elements that we would like to use in our final production version. The aim of the cut down version is to make it as straight forward as possible for participants to submit code for our challenge.

The main elements of the cut down version include some base meta and supplementary data and then a standardised schema for information, warning and error items. For our production version we would like to include additional elements and structures for Goodtables integration and metrics. We have designed our cut down version so it can be easily converted to be Goodtables compatible.

Here is a sample of the JSON structure we are looking at as our cut down version:

    {
      "version": 1,
      "item-count": 0,
      "issue-count": 0,
      "format": "",
      "info": [],
      "warnings": [],
      "errors": [],
      "supplementary":[
        {
          "name": "",
          "role": "",
          "source": ""
        }
      ]
    }

Each object in the info, warnings and errors collections would then have the following structure:

    {
      "processor": "",
      "code": "",
      "message": "",
      "item": {
        "itemType": "",
        "location": {},
        "definition": [],
        "attributes": {}
      },
      "context": [
        {
          "itemType": "",
          "location": {},
          "definition": [],
          "attributes": {}
        }
      ],
      "error-data": {}
    }

We have also come up with a validation schema for this structure to allow us to quickly validate the schema. If you are interested in the schema you can view it here https://gist.github.com/flashharry82/11eca67f787a77b2da3f238b6c8b3e87

Also, here is a sample of a JSON file we validated against this schema https://gist.github.com/flashharry82/dc39d3c0c77842ca4ea012e8618ae184

The following structure is an additional section we are considering for adding metrics.

    "metrics": [
      {
        "metricType": "",
        "name": "",
        "description": "",
        "value": 1
      }
    ]

**Comment by rufuspollock** [comment]
@flashharry82 thanks for submitting this - really useful. Do you use this on tabular data or any kind of data? Interesting to compare this against good tables current output.

**Comment by flashharry82** [comment]
We will be using this on other types of data including geojson. There has also been some discussions around 3D data but that would probably require some further testing.
Goodtables was our starting point and we can easily add in the required structure to make our structure compatible with Goodtables e.g. Putting our single table approach as an array of 1 table and append a table-count of 1 to satisfy the Goodtables format. We may even do this as a matter of course for our production version.

**Comment by rufuspollock** [comment]
@flashharry82 that's great. Converging on goodtables format would be good and if you have specific mods it would be good to know what they are so we can modify if need be.

**Comment by philtweir** [comment]
Apologies for long delay - just to update on this, we have been looking a little this week at tidying some of our reporting format - we are working with real-world data hands-on, and trying to use this to refine some of the early extension features described, and will feed back as we progress
