### ISSUE TITLE
General goodtables-py update

### ISSUE THREAD

**Issue by roll** [frictionlessdata/software#38]
# Overview

The `goodtables-py` library is the user of all our underlying stack and a "face" of all Python implementations. It's become slightly rusty code-wise lately because a lot of people have been working on it (including Vitor's massive changes) and it's kinda slow because it's never been optimized to be fast (our focus has always been on minimal memory consumption).

# Tasks

- [ ] clean up `inspector/validate` modules, probably updating some protocols in use (required by the next step)
- [ ] rebase on multi-processing - https://github.com/frictionlessdata/goodtables-py/issues/255
- [ ] profile/update the whole stack to improve the performance of validation
- [ ] tidy up other parts, especially re-check tests

Estimation: 2-3 days

**Comment by cschloer** [comment]
How does the CDN get updated? I just noticed that the CDN doesn't have the new updates (unless my browser is caching it, which I suppose is highly possible) and want to flag that as a potential issue (perhaps something to do at the very end of this development, as from a local development perspective it's not that important).

**Comment by roll** [comment]
@cschloer 
It's safer to use versioned distributions from UNPKG - https://unpkg.com/goodtables-ui@1.2.3/dist/goodtables-ui.min.css

**Comment by cschloer** [comment]
:+1: thanks
